name: main

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:

  run-arch-image-amd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run Image
      run: docker run --platform linux/amd64 -v $PWD:/workspace quay.io/arbhalerao/arch

  run-arch-image-arm:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run Image
      run: docker run --platform linux/arm64 -v $PWD:/workspace quay.io/arbhalerao/arch

  #   - name: Package cpp lib
  #     run: docker run --platform linux/amd64 -v $PWD:/workspace quay.io/antaris-inc/satos-payload-sdk-tools:stable make cpp_package

  #   - name: Login to image registry
  #     uses: docker/login-action@v2
  #     with:
  #       registry: quay.io
  #       username: ${{ secrets.QUAY_USERNAME }}
  #       password: ${{ secrets.QUAY_PASSWORD }}

  #   - name: Build image
  #     run: docker build -f images/app-cpp/Dockerfile -t quay.io/antaris-inc/satos-payload-app-cpp:${GITHUB_SHA} .

  #   - name: Push image
  #     run: docker push quay.io/antaris-inc/satos-payload-app-cpp:${GITHUB_SHA}

  build-and-publish-arch-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to image registry
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push arch image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 \
          -f arch/Dockerfile \
          -t quay.io/arbhalerao/arch:${GITHUB_SHA} \
          --push .

  build-and-publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to image registry
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push multi-arch image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 \
          -f Dockerfile \
          -t quay.io/arbhalerao/github-workflow:${GITHUB_SHA} \
          --push .