name: main

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:

  # build-and-publish-cpp-app-image:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v1

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2

  #   - name: Build SDK dependencies
  #     run: docker run --platform linux/amd64 -v $PWD:/workspace quay.io/antaris-inc/satos-payload-sdk-tools:stable make api_lib agent_package

  #   - name: Package cpp lib
  #     run: docker run --platform linux/amd64 -v $PWD:/workspace quay.io/antaris-inc/satos-payload-sdk-tools:stable make cpp_package

  #   - name: Login to image registry
  #     uses: docker/login-action@v2
  #     with:
  #       registry: quay.io
  #       username: ${{ secrets.QUAY_USERNAME }}
  #       password: ${{ secrets.QUAY_PASSWORD }}

  #   - name: Build image
  #     run: docker build -f images/app-cpp/Dockerfile -t quay.io/antaris-inc/satos-payload-app-cpp:${GITHUB_SHA} .

  #   - name: Push image
  #     run: docker push quay.io/antaris-inc/satos-payload-app-cpp:${GITHUB_SHA}

  build-and-publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      run: docker build -f Dockerfile -t quay.io/arbhalerao/github-workflow:${GITHUB_SHA} .

    - name: Login to image registry
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Push image
      run: docker push quay.io/antaris-inc/satos-payload-sdk-tools:${GITHUB_SHA}